version: "3"
services:
  web:
    image: nginx
    container_name: web
    ports:
      - 81:80
    depends_on:
      - php
    volumes:
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
      # - ./:/var/www/html

  php:
    build: ./docker/php
    ports:
      - "82:80"
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini

  db:
    image: mysql:5.7
    restart: always
    ports:
      - 3307:3306
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/initdb:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=pwd
      - MYSQL_DATABASE=test
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pwd
